# Generated by Django 3.2.8 on 2021-10-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(blank=True, max_length=999)),
                ('s_code', models.CharField(blank=True, max_length=999)),
                ('s_prefix', models.CharField(choices=[('นาย', 'นาย'), ('นางสาว', 'นางสาว')], max_length=999)),
                ('s_status', models.CharField(blank=True, choices=[('ไม่มีสิทธิ์สัมภาษณ์', 'ไม่มีสิทธิ์สัมภาษณ์'), ('ไม่มาสัมภาษณ์', 'ไม่มาสัมภาษณ์'), ('ผ่านแต่ไม่ชำระเงิน', 'ผ่านแต่ไม่ชำระเงิน'), ('ชำระเงินเรียบร้อย', 'ชำระเงินเรียบร้อย')], max_length=999)),
                ('s_Applicant_type', models.CharField(blank=True, max_length=999)),
                ('s_Faculty_Code', models.CharField(blank=True, max_length=999)),
                ('s_Field_of_study', models.CharField(blank=True, max_length=999)),
                ('s_Year', models.CharField(blank=True, max_length=5)),
                ('s_Thai_Grade', models.FloatField()),
                ('s_Math_Grade', models.FloatField()),
                ('s_Science_Grade', models.FloatField()),
                ('s_Social_studies_Grades', models.FloatField()),
                ('s_Health_education_Grades', models.FloatField()),
                ('s_Art_Grade', models.FloatField()),
                ('s_Career_Grade', models.FloatField()),
                ('s_Foreign_language_Grade', models.FloatField()),
                ('s_GPAX', models.FloatField()),
                ('s_School_Name', models.CharField(blank=True, max_length=999)),
                ('s_Province_Name', models.CharField(blank=True, max_length=999)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
